"""Build a ``sample_prompts.txt`` for sd-scripts from the dataset manifest.

Per-epoch samples are only useful if they are comparable across epochs and
representative of what the model was actually trained on. So this module:

* reads the categories and terms straight out of ``manifest.csv``, rather than
  guessing prompts that may not match the caption distribution at all;
* covers the largest categories, since those dominate what the LoRA learns;
* pins one fixed seed per prompt, so epoch 3 and epoch 9 differ because the
  weights changed and not because the noise did;
* appends a few deliberately out-of-distribution prompts, which are what tell
  you the LoRA has started overfitting to memorised icons.

The generated file is meant to be committed and then hand-edited -- it is a
starting point, not something to regenerate on every run.
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

__all__ = [
    "SampleSettings",
    "read_manifest",
    "category_terms",
    "build_prompt_lines",
    "render_prompt_file",
    "main",
]

DEFAULT_NEGATIVE = "blurry, photo, text, watermark, jpeg artifacts, frame"
DEFAULT_STEPS = 24
DEFAULT_CFG = 7.5
DEFAULT_SEED = 101

#: Combinations that should NOT exist in the training data. If these still look
#: like coherent WoW icons, the LoRA generalised; if they collapse into copies
#: of specific training icons, it has overfitted.
GENERALISATION_PROMPTS: Tuple[str, ...] = (
    "wowicon, weapon, sword, glowing blue runes",
    "wowicon, consumable, potion, swirling green liquid",
    "wowicon, armor, helmet, gilded dragon motif",
    "wowicon, fire spell, spiral of embers",
)


@dataclass(frozen=True)
class SampleSettings:
    """Generation settings shared by every sample prompt."""

    width: int = 512
    height: int = 512
    steps: int = DEFAULT_STEPS
    cfg: float = DEFAULT_CFG
    negative: str = DEFAULT_NEGATIVE
    first_seed: int = DEFAULT_SEED

    def render(self, prompt: str, seed: int) -> str:
        """Render one sd-scripts prompt line with its per-prompt overrides."""
        return (
            f"{prompt} --n {self.negative} --w {self.width} --h {self.height} "
            f"--l {self.cfg} --s {self.steps} --d {seed}"
        )


def read_manifest(path: Path) -> List[Dict[str, str]]:
    """Read ``manifest.csv`` and return its rows."""
    with open(path, "r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"{path} has no rows")
    missing = {"caption", "category"} - set(rows[0])
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")
    return rows


def category_terms(rows: Iterable[Dict[str, str]]) -> Dict[str, Counter]:
    """Count how often each subject term appears within each category."""
    terms: Dict[str, Counter] = defaultdict(Counter)
    for row in rows:
        parts = [part.strip() for part in row["caption"].split(",")]
        category = row["category"].strip()
        # Captions are "<instance token>, <category>, <terms...>", so the
        # subject terms are everything from the third field on.
        for term in parts[2:]:
            if term and term != category:
                terms[category][term] += 1
    return dict(terms)


def build_prompt_lines(
    rows: Sequence[Dict[str, str]],
    settings: Optional[SampleSettings] = None,
    top_categories: int = 8,
    terms_per_category: int = 1,
    generalisation_prompts: Sequence[str] = GENERALISATION_PROMPTS,
    instance_token: str = "wowicon",
) -> List[str]:
    """Build the full list of file lines, comments included."""
    settings = settings or SampleSettings()
    counts = Counter(row["category"].strip() for row in rows)
    terms = category_terms(rows)

    lines = [
        "# Sample prompts for sd-scripts (--sample_prompts).",
        "# Generated by `python -m wowicons.prompts`; edit freely afterwards.",
        "#",
        "# Every prompt pins its own seed (--d) so that differences between",
        "# epochs come from the weights and not from a new noise draw. Keep the",
        "# seeds stable if you want epoch-to-epoch comparisons to mean anything.",
        "#",
        f"# Dataset: {sum(counts.values())} images across {len(counts)} categories.",
        "",
        f"# --- most common categories (top {top_categories}) ---",
    ]

    seed = settings.first_seed
    for category, count in counts.most_common(top_categories):
        share = count / sum(counts.values()) * 100
        lines.append(f"# {category}: {count} images ({share:.1f}% of the set)")
        for term, _ in terms.get(category, Counter()).most_common(
            terms_per_category
        ):
            prompt = f"{instance_token}, {category}, {term}"
            lines.append(settings.render(prompt, seed))
            seed += 1
        if not terms.get(category):
            lines.append(
                settings.render(f"{instance_token}, {category}", seed)
            )
            seed += 1

    if generalisation_prompts:
        lines.extend(
            [
                "",
                "# --- unseen combinations: these should look like plausible WoW",
                "# icons without being copies of any single training image ---",
            ]
        )
        for prompt in generalisation_prompts:
            lines.append(settings.render(prompt, seed))
            seed += 1

    lines.append("")
    return lines


def render_prompt_file(*args, **kwargs) -> str:
    """``build_prompt_lines`` joined into file contents."""
    return "\n".join(build_prompt_lines(*args, **kwargs))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="wowicons.prompts",
        description=(
            "Generate a sample_prompts.txt for sd-scripts from the captions in "
            "a dataset manifest.csv."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--manifest", required=True, type=Path, help="Path to manifest.csv."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Where to write the prompt file. Defaults to stdout.",
    )
    parser.add_argument(
        "--categories",
        type=int,
        default=8,
        help="How many of the largest categories to sample.",
    )
    parser.add_argument(
        "--terms-per-category",
        type=int,
        default=1,
        help="Prompts to emit per category.",
    )
    parser.add_argument("--width", type=int, default=512)
    parser.add_argument("--height", type=int, default=512)
    parser.add_argument("--steps", type=int, default=DEFAULT_STEPS)
    parser.add_argument("--cfg", type=float, default=DEFAULT_CFG)
    parser.add_argument("--negative", default=DEFAULT_NEGATIVE)
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Seed for the first prompt; later prompts increment from it.",
    )
    parser.add_argument(
        "--instance-token",
        default="wowicon",
        help="Trigger word the prompts start with.",
    )
    parser.add_argument(
        "--no-generalisation-prompts",
        action="store_true",
        help="Skip the deliberately unseen prompt combinations.",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        rows = read_manifest(args.manifest)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    text = render_prompt_file(
        rows,
        settings=SampleSettings(
            width=args.width,
            height=args.height,
            steps=args.steps,
            cfg=args.cfg,
            negative=args.negative,
            first_seed=args.seed,
        ),
        top_categories=args.categories,
        terms_per_category=args.terms_per_category,
        generalisation_prompts=()
        if args.no_generalisation_prompts
        else GENERALISATION_PROMPTS,
        instance_token=args.instance_token,
    )

    if args.output is None:
        print(text)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        prompts = sum(
            1 for line in text.splitlines() if line and not line.startswith("#")
        )
        print(f"Wrote {prompts} sample prompts to {args.output}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
